### PR TITLE
Use reasonably maximal warning level for MSVS projects

### PR DESCRIPTION
**Pull request by vadz**
Use bakefile "all" warnings level and fix two warnings that appeared when
using it with MSVS 2015.

### CODE REVIEW

**Comment by vslavik** [comment]
The list of commits here doesn’t seem right...

**Comment by vadz** [comment]
Sorry, that's because I opened it from my own master and forgot about it and updated master later.

The only commit that was really supposed to be here is [this one](https://github.com/vslavik/xmlwrapp/pull/34/commits/527981600e0bff8aa5909ad4408f91eb85883fa6)

**Comment by vslavik** [comment]
> The only commit that was really supposed to be here is this one

No comments from me, then :)

**Comment by vadz** [comment]
Thanks, I was going to update this PR with just it but didn't really know how to do it, so I'm glad I don't have to, now...

**Pull request closed without merging**
