### PR TITLE
Fix sporadic memory access crashes when built on MacOS using clang 12

### PR DESCRIPTION
**Pull request by SergeySatskiy**

### CODE REVIEW

**Comment by vslavik** [comment]
The old code was certainly wrong — I'm more surprised by your reference to a specific compiler and *sporadic* crashes where I'd expect this to be libxml2 version dependent and wreaking havoc reliably...

I'd prefer to avoid the allocation there, though. Would having a stack-allocated `xmlDoc temp_to_test_replace_success = {0}` work instead? Looking at `xmlNewDoc()` I think it *should*, but...

**Comment by vadz** [comment]
I'm not really sure what this code does, so I wanted to reproduce the problem before fixing it and it turns out I can't do it, at least under macOS 12 with clang 13.1.6 with the system libxml2 2.9.4.

Can you reproduce it with the existing unit tests (notably `node/replace` which exercises this code)? If so, what is your clang/macOS/libxml2 versions? If not, could you please add a unit test allowing to reproduce the problem?

**Comment by SergeySatskiy** [comment]
@vslavik, as you probably know, we at NCBI use a fork of xmlwrapp. We support multiple platforms and a bunch of the compilers and a few configurations for each of the compilers. We use as well a testing system which supports all supported permutations on everyday basis with test reports. Recently errors started to appear in the reports sporadically for one of the xmlwrapp tests. The investigation showed that it happened only on Mac OS and only since clang 12 was included into the list of supported compilers. It has never been a problem with e.g. xcode. Moreover, manual runs revealed that the crash never happens when the build is in debug configuration. When the build is in release configuration then about 3 out of 5 runs of the very same binary go well with no problems while 2 runs crash - still with the same binary. This is why I used the word "sporadic" in the description of the fix.

I would also prefer to avoid allocations however a few factors stopped me from doing this:
- it is unknown and uncontrollable how libxml2 code will be changed in the future and what it will do with the document pointer
- I wanted a reliable solution which I will not need to get back later, especially bearing in mind a sporadic nature of the problem
- In our case the functionality of node replacement is used rather very rare so that there will be no meaningful performance impact

All in all, please feel free to reject my proposal and introduce your own. I just wanted to let you know and make a suggestion for your version of the library. It will not affect our version anyway.

@vadz, I spotted the problem on our tests which are not exactly the same as yours however your node/replace test should expose the same behavior.

**Comment by vadz** [comment]
Sorry, it still isn't clear to me whether you can reproduce the crash with node/replace test or not? If you can, could it be due to some changes in your fork (is it public?)? Have you tried using ASAN and does it provide more information in your case?

**Comment by vadz** [comment]
It's not that I doubt your words, but I have a lot of trouble with fixing a bug that

1. I can't reproduce.
2. I have no information about (other than it happens).

I'm afraid I'm going to leave it to Vaclav to decide what to do about it.

**Comment by SergeySatskiy** [comment]
I understand, I also had troubles to reproduce it and to understand why it crashes sporadically.

**Comment by vadz** [comment]
Sorry, it took me embarrassingly long to realize it, but this has nothing to do with the compiler version, but all to do with libxml2 version: the bug happens with v2.10.3 and I do see it when using it. In fact it is due to https://github.com/GNOME/libxml2/commit/4bc3ebf3eaba352fbbce2ef70ad00a3c7752478a which is present in v2.10.0+ and now actually uses `doc` member of the new node, while it was unused before.

I've created #87 fixing this in the way similar to this PR, but without the extra heap allocation, as suggested by Vaclav, which seems better, so I'm closing this one and will merge the other PR if there are no objections.

Thanks for reporting this and sorry again for failing to see the real problem for so long...

**Pull request closed without merging**
